name: Test and NuGet publish on version change

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    working-directory: ./src
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.405

    - name: Test
      run: dotnet test --configuration Debug --verbosity normal Errorka.Tests

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.405

    - name: Publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ./src/Errorka/Errorka.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        BUILD_CONFIGURATION: Release
        TAG_COMMIT: true
        TAG_FORMAT: v*
        NUGET_KEY: ${{secrets.NUGETKEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: true